In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, confusion_matrix

low_memory = False

columns = ['feat_1','feat_2','feat_3',
           'feat_4','feat_5','feat_6','feat_7',
           'feat_8','feat_9','feat_10','feat_11',
           'feat_12','feat_13','feat_14','feat_15',
           'feat_16','feat_17','feat_18','feat_19',
           'feat_20','feat_21','feat_22','feat_23',
           'feat_24','feat_25','feat_26','feat_27',
           'feat_28','feat_29','feat_30','feat_31',
           'feat_32','feat_33','feat_34','feat_35',
           'feat_36','feat_37','feat_38','feat_39',
           'feat_40','feat_41','feat_42','feat_43',
           'feat_44','feat_45','feat_46','feat_47',
           'feat_48','feat_49','feat_50','feat_51',
           'feat_52','feat_53','feat_54','feat_55',
           'feat_56','feat_57','feat_58','feat_59',
           'feat_60','feat_61','feat_62','feat_63',
           'feat_64','feat_65','feat_66','feat_67',
           'feat_68','feat_69','feat_70','feat_71',
           'feat_72','feat_73','feat_74','feat_75',
           'feat_76','feat_77','feat_78','feat_79',
           'feat_80','feat_81','feat_82','feat_83',
           'feat_84','feat_85','feat_86','feat_87',
           'feat_88','feat_89','feat_90','feat_91',
           'feat_92','feat_93','target']


dataset = pd.read_csv('train.csv',names=columns)

X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, 4].values

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)

print(X)
#scaler = StandardScaler()
#scaler.fit(X_train)

#X_train = scaler.transform(X_train)
#X_test = scaler.transform(X_test)

#classifier = KNeighborsClassifier(n_neighbors=5)
#classifier.fit(X_train, y_train)

#y_pred = classifier.predict(X_test)

#print(confusion_matrix(y_test, y_pred))
#print(classification_report(y_test, y_pred))

#print(X)
print(y)




C:\murach\SpyderPython\lib\site-packages\IPython\core\interactiveshell.py:3057: DtypeWarning: Columns (0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


[['feat_1' 'feat_2' 'feat_3' ... 'feat_91' 'feat_92' 'feat_93']
 ['1' '0' '0' ... '0' '0' '0']
 ['0' '0' '0' ... '0' '0' '0']
 ...
 [0 0 0 ... 0 0 0]
 [1 0 0 ... 3 10 0]
 [0 0 0 ... 0 2 0]]
['feat_5' '0' '0' ... 0 0 0]
